#ifndef INLINE4_FRIBIDI_H
#define INLINE4_FRIBIDI_H

/*
** This file was machine generated by idltool.py 54.8.
** Do not edit.
**
** It provides compatibility to AmigaOS 3.x style library
** calls by substituting functions.
*/

#include <exec/types.h>
#include <exec/exec.h>
#include <exec/interfaces.h>


/* Inline macros for Interface "main" */
#define fribidi_get_joining_type(ch) IFriBidi->fribidi_get_joining_type((ch))
#define fribidi_get_joining_types(str, len, jtypes) IFriBidi->fribidi_get_joining_types((str), (len), (jtypes))
#define fribidi_get_joining_type_name(j) IFriBidi->fribidi_get_joining_type_name((j))
#define fribidi_shape_arabic(flags, embedding_levels, len, ar_props, str) IFriBidi->fribidi_shape_arabic((flags), (embedding_levels), (len), (ar_props), (str))
#define fribidi_get_par_direction(bidi_types, len) IFriBidi->fribidi_get_par_direction((bidi_types), (len))
#define fribidi_get_par_embedding_levels_ex(bidi_types, bracket_types, len, pbase_dir, embedding_levels) IFriBidi->fribidi_get_par_embedding_levels_ex((bidi_types), (bracket_types), (len), (pbase_dir), (embedding_levels))
#define fribidi_reorder_line(flags, bidi_types, len, off, base_dir, embedding_levels, visual_str, map) IFriBidi->fribidi_reorder_line((flags), (bidi_types), (len), (off), (base_dir), (embedding_levels), (visual_str), (map))
#define fribidi_get_bracket(ch) IFriBidi->fribidi_get_bracket((ch))
#define fribidi_get_bracket_types(str, len, types, btypes) IFriBidi->fribidi_get_bracket_types((str), (len), (types), (btypes))
#define fribidi_charset_to_unicode(char_set, s, len, us) IFriBidi->fribidi_charset_to_unicode((char_set), (s), (len), (us))
#define fribidi_unicode_to_charset(char_set, us, len, s) IFriBidi->fribidi_unicode_to_charset((char_set), (us), (len), (s))
#define fribidi_parse_charset(s) IFriBidi->fribidi_parse_charset((s))
#define fribidi_char_set_name(char_set) IFriBidi->fribidi_char_set_name((char_set))
#define fribidi_char_set_title(char_set) IFriBidi->fribidi_char_set_title((char_set))
#define fribidi_char_set_desc(char_set) IFriBidi->fribidi_char_set_desc((char_set))
#define fribidi_debug_status() IFriBidi->fribidi_debug_status()
#define fribidi_set_debug(state) IFriBidi->fribidi_set_debug((state))
#define fribidi_join_arabic(bidi_types, len, embedding_levels, ar_props) IFriBidi->fribidi_join_arabic((bidi_types), (len), (embedding_levels), (ar_props))
#define fribidi_get_mirror_char(ch, mirrored_ch) IFriBidi->fribidi_get_mirror_char((ch), (mirrored_ch))
#define fribidi_shape_mirroring(embedding_levels, len, str) IFriBidi->fribidi_shape_mirroring((embedding_levels), (len), (str))
#define fribidi_shape(flags, embedding_levels, len, ar_props, str) IFriBidi->fribidi_shape((flags), (embedding_levels), (len), (ar_props), (str))
#define fribidi_remove_bidi_marks(str, len, positions_to_this, position_from_this_list, embedding_levels) IFriBidi->fribidi_remove_bidi_marks((str), (len), (positions_to_this), (position_from_this_list), (embedding_levels))
#define fribidi_log2vis(str, len, pbase_dir, visual_str, positions_L_to_V, positions_V_to_L, embedding_levels) IFriBidi->fribidi_log2vis((str), (len), (pbase_dir), (visual_str), (positions_L_to_V), (positions_V_to_L), (embedding_levels))
#define fribidi_get_bidi_type(ch) IFriBidi->fribidi_get_bidi_type((ch))
#define fribidi_get_bidi_types(str, len, btypes) IFriBidi->fribidi_get_bidi_types((str), (len), (btypes))
#define fribidi_get_bidi_type_name(t) IFriBidi->fribidi_get_bidi_type_name((t))
#define fribidi_mirroring_status() IFriBidi->fribidi_mirroring_status()
#define fribidi_set_mirroring(state) IFriBidi->fribidi_set_mirroring((state))
#define fribidi_reorder_nsm_status() IFriBidi->fribidi_reorder_nsm_status()
#define fribidi_set_reorder_nsm(state) IFriBidi->fribidi_set_reorder_nsm((state))
#define fribidi_log2vis_get_embedding_levels(bidi_types, len, pbase_dir, embedding_levels) IFriBidi->fribidi_log2vis_get_embedding_levels((bidi_types), (len), (pbase_dir), (embedding_levels))
#define fribidi_get_type(ch) IFriBidi->fribidi_get_type((ch))
#define fribidi_get_type_internal(ch) IFriBidi->fribidi_get_type_internal((ch))
#define fribidi_get_par_embedding_levels(bidi_types, len, pbase_dir, embedding_levels) IFriBidi->fribidi_get_par_embedding_levels((bidi_types), (len), (pbase_dir), (embedding_levels))

#endif /* INLINE4_FRIBIDI_H */
