#ifndef PROTO_FRIBIDI_H
#define PROTO_FRIBIDI_H

/*
** This file was machine generated by idltool.py 54.8.
** Do not edit.
**
** Prototype/inline/pragma header file combo.
*/

#include <fribidi.h>

/****************************************************************************/

#ifndef __NOLIBBASE__
 #ifndef __USE_BASETYPE__
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::Library * FriBidiBase;
  #else
   extern struct Library * FriBidiBase;
  #endif
 #else
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::FriBidiLibrary * FriBidiBase;
  #else
   extern struct FriBidiLibrary * FriBidiBase;
  #endif
 #endif /* __USE_BASETYPE__ */
#endif /* __NOLIBBASE__ */

/****************************************************************************/

#ifdef __amigaos4__
 #include <interfaces/fribidi.h>
 #ifdef __USE_INLINE__
  #include <inline4/fribidi.h>
 #endif /* __USE_INLINE__ */
 #ifndef CLIB_FRIBIDI_PROTOS_H
  #define CLIB_FRIBIDI_PROTOS_H 1
 #endif /* CLIB_FRIBIDI_PROTOS_H */
 #ifndef __NOGLOBALIFACE__
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::FriBidiIFace * IFriBidi;
  #else
   extern struct FriBidiIFace * IFriBidi;
  #endif
 #endif /* __NOGLOBALIFACE__ */
#else /* __amigaos4__ */
 #ifndef CLIB_FRIBIDI_PROTOS_H
  #include <clib/fribidi_protos.h>
 #endif /* CLIB_FRIBIDI_PROTOS_H */
 #if defined(__GNUC__)
  #ifndef __PPC__
   #include <inline/fribidi.h>
  #else /* __PPC__ */
   #include <ppcinline/fribidi.h>
  #endif /* __PPC__ */
 #elif defined(__VBCC__)
  #ifndef __PPC__
   #include <inline/fribidi_protos.h>
  #endif /* __PPC__ */
 #else /* __GNUC__ */
  #include <pragmas/fribidi_pragmas.h>
 #endif /* __GNUC__ */
#endif /* __amigaos4__ */

/****************************************************************************/

#endif /* PROTO_FRIBIDI_H */
