#ifndef FRIBIDI_INTERFACE_DEF_H
#define FRIBIDI_INTERFACE_DEF_H
/*
** This file was machine generated by idltool.py 54.8.
** Do not edit.
*/

#include <exec/types.i>
#include <exec/exec.i>
#include <exec/interfaces.i>

STRUCTURE FriBidiIFace, InterfaceData_SIZE
	    FPTR IFriBidi_Obtain
	    FPTR IFriBidi_Release
	    FPTR FriBidiIFace_Expunge_UNIMPLEMENTED
	    FPTR FriBidiIFace_Clone_UNIMPLEMENTED
	    FPTR IFriBidi_fribidi_get_joining_type
	    FPTR IFriBidi_fribidi_get_joining_types
	    FPTR IFriBidi_fribidi_get_joining_type_name
	    FPTR IFriBidi_fribidi_shape_arabic
	    FPTR IFriBidi_fribidi_get_par_direction
	    FPTR IFriBidi_fribidi_get_par_embedding_levels_ex
	    FPTR IFriBidi_fribidi_reorder_line
	    FPTR IFriBidi_fribidi_get_bracket
	    FPTR IFriBidi_fribidi_get_bracket_types
	    FPTR IFriBidi_fribidi_charset_to_unicode
	    FPTR IFriBidi_fribidi_unicode_to_charset
	    FPTR IFriBidi_fribidi_parse_charset
	    FPTR IFriBidi_fribidi_char_set_name
	    FPTR IFriBidi_fribidi_char_set_title
	    FPTR IFriBidi_fribidi_char_set_desc
	    FPTR IFriBidi_fribidi_debug_status
	    FPTR IFriBidi_fribidi_set_debug
	    FPTR IFriBidi_fribidi_join_arabic
	    FPTR IFriBidi_fribidi_get_mirror_char
	    FPTR IFriBidi_fribidi_shape_mirroring
	    FPTR IFriBidi_fribidi_shape
	    FPTR IFriBidi_fribidi_remove_bidi_marks
	    FPTR IFriBidi_fribidi_log2vis
	    FPTR IFriBidi_fribidi_get_bidi_type
	    FPTR IFriBidi_fribidi_get_bidi_types
	    FPTR IFriBidi_fribidi_get_bidi_type_name
	    FPTR IFriBidi_fribidi_mirroring_status
	    FPTR IFriBidi_fribidi_set_mirroring
	    FPTR IFriBidi_fribidi_reorder_nsm_status
	    FPTR IFriBidi_fribidi_set_reorder_nsm
	    FPTR IFriBidi_fribidi_log2vis_get_embedding_levels
	    FPTR IFriBidi_fribidi_get_type
	    FPTR IFriBidi_fribidi_get_type_internal
	    FPTR IFriBidi_fribidi_get_par_embedding_levels
	LABEL FriBidiIFace_SIZE

#endif /* FRIBIDI_INTERFACE_DEF_H */
