/*
** This file was machine generated by idltool.py 54.8.
** Do not edit.
*/

#include "fribidi_vectors.h"

STATIC uint32 VARARGS68K _impl_UNIMPLEMENTED(struct FriBidiIFace *iface UNUSED)
{
  return 0;
}
STATIC CONST APTR main_v1_vectors[] =
{
    _impl_Obtain,
    _impl_Release,
    _impl_UNIMPLEMENTED, /* Expunge */
    _impl_UNIMPLEMENTED, /* Clone */
    _impl_fribidi_get_joining_type,
    _impl_fribidi_get_joining_types,
    _impl_fribidi_get_joining_type_name,
    _impl_fribidi_shape_arabic,
    _impl_fribidi_get_par_direction,
    _impl_fribidi_get_par_embedding_levels_ex,
    _impl_fribidi_reorder_line,
    _impl_fribidi_get_bracket,
    _impl_fribidi_get_bracket_types,
    _impl_fribidi_charset_to_unicode,
    _impl_fribidi_unicode_to_charset,
    _impl_fribidi_parse_charset,
    _impl_fribidi_char_set_name,
    _impl_fribidi_char_set_title,
    _impl_fribidi_char_set_desc,
    _impl_fribidi_debug_status,
    _impl_fribidi_set_debug,
    _impl_fribidi_join_arabic,
    _impl_fribidi_get_mirror_char,
    _impl_fribidi_shape_mirroring,
    _impl_fribidi_shape,
    _impl_fribidi_remove_bidi_marks,
    _impl_fribidi_log2vis,
    _impl_fribidi_get_bidi_type,
    _impl_fribidi_get_bidi_types,
    _impl_fribidi_get_bidi_type_name,
    _impl_fribidi_mirroring_status,
    _impl_fribidi_set_mirroring,
    _impl_fribidi_reorder_nsm_status,
    _impl_fribidi_set_reorder_nsm,
    _impl_fribidi_log2vis_get_embedding_levels,
    _impl_fribidi_get_type,
    _impl_fribidi_get_type_internal,
    _impl_fribidi_get_par_embedding_levels,
    (APTR)-1
};
